In [3]:
import numpy as np
import pandas as pd
import matplotlib as plt
import sympy as smp
from sympy.solvers import solve
from sympy import Symbol
Matrix=np.random.randint(1,10,size=(3,3))
print(Matrix)


[[7 8 3]
 [4 1 2]
 [6 8 6]]


In [4]:
def SVDSetupU(Matrix):
    #Build array, and transpose of that array
    Matrix=np.array(Matrix).copy()

    Transpose=np.transpose(Matrix)
    #Perform Matrix Multiplication to find AAt and AtA Matrices
    MultipliedU=np.dot(Matrix, Transpose)

    return MultipliedU
print(SVDSetupU(Matrix))

[[122  42 124]
 [ 42  21  44]
 [124  44 136]]


In [5]:
def SVDSetupV(Matrix):
    Matrix=np.array(Matrix).copy()

    Transpose=np.transpose(Matrix)

    MultipliedV=np.dot(Transpose, Matrix)
    return MultipliedV
print(SVDSetupV(Matrix))

[[101 108  65]
 [108 129  74]
 [ 65  74  49]]


In [13]:
MultipliedU=SVDSetupU(Matrix)
def EigenvaluesU(MultipliedU):
    values_U,_=np.linalg.eig(MultipliedU)
    return values_U
print(EigenvaluesU(MultipliedU))

[268.16673057   4.73665325   6.09661617]


In [15]:
MultipliedV=SVDSetupV(Matrix)
def EigenvaluesV(MultipliedV):
    values_V,_=np.linalg.eig(MultipliedV)
    return values_V 
print(EigenvaluesV(MultipliedV))

[268.16673057   6.09661617   4.73665325]


In [16]:
values_U=EigenvaluesU(MultipliedU)
def SingularValues(values_U):
    Sing_Values=np.sqrt(values_U)
    Sing_Values=np.sort(Sing_Values)[::-1]
    return Sing_Values
print(SingularValues(values_U))

[16.3757971   2.46913268  2.17638536]


In [17]:
Sing_Values=SingularValues(values_U)
def CreateSVArray(Sing_Values, Matrix):
    rows, columns=Matrix.shape
    length=min(rows,columns)
    padded_zero_values= np.pad(Sing_Values,(0,length-len(Sing_Values)),'constant')
    SV_Array=np.zeros((rows,columns), dtype=float)
    np.fill_diagonal(SV_Array, padded_zero_values)
    return SV_Array
print(CreateSVArray(Sing_Values,Matrix))

[[16.3757971   0.          0.        ]
 [ 0.          2.46913268  0.        ]
 [ 0.          0.          2.17638536]]


In [18]:
MultipliedU=SVDSetupU(Matrix)
def EigenvectorsU(MultipliedU):
    _,vectors_U=np.linalg.eig(MultipliedU)
    return vectors_U
print(EigenvectorsU(MultipliedU))

[[-6.67188363e-01 -7.44889025e-01  1.71451000e-04]
 [-2.38966901e-01  2.13821835e-01 -9.47193245e-01]
 [-7.05517192e-01  6.31997281e-01  3.20663262e-01]]


In [19]:
MultipliedV=SVDSetupV(Matrix)
def EigenvectorsV(MultipliedV):
    #Find Eigenvectors of AAt and AtA
    _,vectors_V=np.linalg.eig(MultipliedV)
    return vectors_V
print(EigenvectorsV(MultipliedV))

[[-0.6020647  -0.75475622 -0.26050173]
 [-0.68519482  0.65589204 -0.31672337]
 [-0.40990994  0.01219353  0.91204449]]


In [20]:
vectors_U=EigenvectorsU(MultipliedU)
def MatrixU(vectors_U):
#Build matrix U, which consists of the Eigenvectors of AAt
    matrix_U=np.array(vectors_U)
    magnitude=np.linalg.norm(matrix_U, axis=0)
    matrix_U=matrix_U/magnitude


    return matrix_U
print(MatrixU(vectors_U))

[[-6.67188363e-01 -7.44889025e-01  1.71451000e-04]
 [-2.38966901e-01  2.13821835e-01 -9.47193245e-01]
 [-7.05517192e-01  6.31997281e-01  3.20663262e-01]]


In [21]:
vectors_V=EigenvectorsV(MultipliedV)
def MatrixV(vectors_V):
#Build Matrix V, which consists of the Eigenvectors of AtA
    matrix_V=np.array(vectors_V.T)
    return matrix_V
print(MatrixV(vectors_V))

[[-0.6020647  -0.68519482 -0.40990994]
 [-0.75475622  0.65589204  0.01219353]
 [-0.26050173 -0.31672337  0.91204449]]


In [22]:
matrix_U=MatrixU(vectors_U)
SV_Array=CreateSVArray(Sing_Values,Matrix)
matrix_V=MatrixV(vectors_V)
def SVDBuild(matrix_U,SV_Array,matrix_V):
#Perform Singular Value Decomposition, the dot product of Matrices U and A, and the Singular Values Array
    SVD=np.dot(matrix_U, np.dot(SV_Array, matrix_V.T))
    SVD=np.abs(SVD)

    return SVD
print(SVDBuild(matrix_U,SV_Array,matrix_V))
check=np.linalg.svd(Matrix)
print(check)

[[7.83808088 7.03993953 3.42904184]
 [2.83930407 3.27471221 1.027942  ]
 [5.60059102 9.75202482 3.15194402]]
SVDResult(U=array([[-6.67188363e-01,  1.71451000e-04, -7.44889025e-01],
       [-2.38966901e-01, -9.47193245e-01,  2.13821835e-01],
       [-7.05517192e-01,  3.20663262e-01,  6.31997281e-01]]), S=array([16.3757971 ,  2.46913268,  2.17638536]), Vh=array([[-0.6020647 , -0.68519482, -0.40990994],
       [-0.75475622,  0.65589204,  0.01219353],
       [-0.26050173, -0.31672337,  0.91204449]]))
