In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import sympy as smp
from sympy.solvers import solve
from sympy import Symbol
import scipy as sp
Matrix=np.random.randint(1,10,size=(3,3))
print(Matrix)

[[7 3 2]
 [4 4 1]
 [1 4 3]]


In [2]:
def SVDSetupU(Matrix):
    Matrix=np.array(Matrix).copy()
    Transpose=np.transpose(Matrix)
    MultipliedU=np.dot(Matrix, Transpose)
    return MultipliedU
print(SVDSetupU(Matrix))

[[62 42 25]
 [42 33 23]
 [25 23 26]]


In [3]:
def SVDSetupV(Matrix):
    Matrix=np.array(Matrix).copy()
    Transpose=np.transpose(Matrix)
    MultipliedV=np.dot(Transpose, Matrix)
    return MultipliedV
print(SVDSetupV(Matrix))

[[66 41 21]
 [41 41 22]
 [21 22 14]]


In [4]:
MultipliedU=SVDSetupU(Matrix)

def EigenvaluesU(MultipliedU):
    values_U,_=np.linalg.eig(MultipliedU)
    return values_U
    return vectors_U
print(EigenvaluesU(MultipliedU))

[106.1405743   13.29389316   1.56553254]


In [6]:
MultipliedV=SVDSetupV(Matrix)
def EigenvaluesV(MultipliedV):
    values_V,_=np.linalg.eig(MultipliedV)
    return values_V 
print(EigenvaluesV(MultipliedV))

[106.1405743   13.29389316   1.56553254]


In [8]:
values_U=EigenvaluesU(MultipliedU)
def SingularValues(values_U):
    Sing_Values=np.sqrt(values_U)
    Sing_Values=np.sort(Sing_Values)[::-1]
    return Sing_Values
print(SingularValues(values_U))

[10.30245477  3.64607915  1.25121243]


In [9]:
Sing_Values=SingularValues(values_U)
def CreateSVArray(Sing_Values, Matrix):
    rows, columns=Matrix.shape
    length=min(rows,columns)
    padded_zero_values= np.pad(Sing_Values,(0,length-len(Sing_Values)),'constant')
    SV_Array=np.zeros((rows,columns), dtype=float)
    np.fill_diagonal(SV_Array, padded_zero_values)
    return SV_Array
print(CreateSVArray(Sing_Values,Matrix))

[[10.30245477  0.          0.        ]
 [ 0.          3.64607915  0.        ]
 [ 0.          0.          1.25121243]]


In [10]:
MultipliedU=SVDSetupU(Matrix)
def EigenvectorsU(MultipliedU):
    _,vectors_U=np.linalg.eig(MultipliedU)
    return vectors_U
print(EigenvectorsU(MultipliedU))

[[-0.74108725 -0.5058225   0.4415125 ]
 [-0.54768658  0.07505948 -0.83330996]
 [-0.38836723  0.85936586  0.33265781]]


In [11]:
MultipliedV=SVDSetupV(Matrix)
def EigenvectorsV(MultipliedV):
    _,vectors_V=np.linalg.eig(MultipliedV)
    return vectors_V
print(EigenvectorsV(MultipliedV))

[[ 0.75387123  0.65307241  0.07193462]
 [ 0.57922865 -0.60893737 -0.54193122]
 [ 0.31011665 -0.45021295  0.83733862]]


In [12]:
vectors_U=EigenvectorsU(MultipliedU)
def MatrixU(vectors_U):
    matrix_U=np.array(vectors_U)
    magnitude=np.linalg.norm(matrix_U, axis=0)
    matrix_U=matrix_U/magnitude
    return matrix_U
print(MatrixU(vectors_U))

[[-0.74108725 -0.5058225   0.4415125 ]
 [-0.54768658  0.07505948 -0.83330996]
 [-0.38836723  0.85936586  0.33265781]]


In [13]:
vectors_V=EigenvectorsV(MultipliedV)
def MatrixV(vectors_V):
    matrix_V=np.array(vectors_V.T)
    return matrix_V
print(MatrixV(vectors_V))

[[ 0.75387123  0.57922865  0.31011665]
 [ 0.65307241 -0.60893737 -0.45021295]
 [ 0.07193462 -0.54193122  0.83733862]]


In [14]:
matrix_U=MatrixU(vectors_U)
SV_Array=CreateSVArray(Sing_Values,Matrix)
matrix_V=MatrixV(vectors_V)
def SVDBuild(matrix_U,SV_Array,matrix_V):
#Perform Singular Value Decomposition, the dot product of Matrices U and A, and the Singular Values Array
    SVD=np.dot(matrix_U, np.dot(SV_Array, matrix_V.T))
    SVD=np.abs(SVD)

    return SVD
print(SVDBuild(matrix_U,SV_Array,matrix_V))
check=np.linalg.svd(Matrix)
print(check)

[[6.65275722 4.11188461 0.91281231]
 [4.41855394 3.3822077  1.42725336]
 [1.07235632 4.70841471 1.63734017]]
SVDResult(U=array([[-0.74108725,  0.5058225 ,  0.4415125 ],
       [-0.54768658, -0.07505948, -0.83330996],
       [-0.38836723, -0.85936586,  0.33265781]]), S=array([10.30245477,  3.64607915,  1.25121243]), Vh=array([[-0.75387123, -0.57922865, -0.31011665],
       [ 0.65307241, -0.60893737, -0.45021295],
       [ 0.07193462, -0.54193122,  0.83733862]]))
