In [2]:
import numpy as np

Matrix=np.random.rand(500,500)
print(Matrix)

[[0.95500275 0.3219093  0.81529228 ... 0.33044257 0.41132958 0.24150307]
 [0.45281358 0.97283125 0.54606819 ... 0.35635918 0.88729179 0.22251841]
 [0.25287725 0.72683524 0.58493354 ... 0.58377018 0.73465073 0.70194448]
 ...
 [0.02909837 0.18867689 0.49458843 ... 0.41780859 0.47826577 0.06111002]
 [0.85757125 0.19139365 0.84403295 ... 0.9246525  0.3105538  0.95071065]
 [0.10188313 0.79049771 0.40927175 ... 0.1183571  0.47762046 0.81620938]]


In [3]:
def SVDSetupU(Matrix):
    Matrix=np.array(Matrix).copy()
    Transpose=np.transpose(Matrix)
    MultipliedU=np.dot(Matrix, Transpose)
    return MultipliedU
print(SVDSetupU(Matrix))

[[173.23505642 136.16116512 126.72764759 ... 125.5866772  125.5519552
  130.82353757]
 [136.16116512 178.04261316 129.36131963 ... 127.6309173  127.32922165
  134.14240696]
 [126.72764759 129.36131963 168.42773719 ... 122.70715762 122.62605368
  129.04270295]
 ...
 [125.5866772  127.6309173  122.70715762 ... 168.95872037 125.33928548
  131.20863527]
 [125.5519552  127.32922165 122.62605368 ... 125.33928548 167.42330536
  131.70090608]
 [130.82353757 134.14240696 129.04270295 ... 131.20863527 131.70090608
  176.18075479]]


In [4]:
def SVDSetupV(Matrix):
    Matrix=np.array(Matrix).copy()
    Transpose=np.transpose(Matrix)
    MultipliedV=np.dot(Transpose, Matrix)
    return MultipliedV
print(SVDSetupV(Matrix))

[[174.88511732 129.9445057  124.62134884 ... 129.98550188 123.86182968
  121.45214505]
 [129.9445057  176.41396851 125.09778873 ... 127.3369357  127.16030539
  121.38029531]
 [124.62134884 125.09778873 164.04683739 ... 127.86797917 122.2458847
  117.58473764]
 ...
 [129.98550188 127.3369357  127.86797917 ... 171.91440625 128.40184324
  123.53663554]
 [123.86182968 127.16030539 122.2458847  ... 128.40184324 165.48650346
  119.42596499]
 [121.45214505 121.38029531 117.58473764 ... 123.53663554 119.42596499
  154.14664197]]


In [5]:
MultipliedU=SVDSetupU(Matrix)

def EigenvaluesU(MultipliedU):
    values_U,_=np.linalg.eig(MultipliedU)
    return values_U
    return vectors_U
print(EigenvaluesU(MultipliedU))

[6.25760478e+04 1.63428454e+02 1.61253855e+02 1.58353491e+02
 1.56122326e+02 1.53664354e+02 1.52445092e+02 1.50561320e+02
 1.47639034e+02 1.47023322e+02 1.46675680e+02 1.45358785e+02
 1.43374655e+02 1.42130347e+02 1.41602842e+02 1.39920562e+02
 1.38916129e+02 1.37803399e+02 1.37131130e+02 1.34522422e+02
 1.33984396e+02 1.32668668e+02 1.31546758e+02 1.27354965e+02
 1.27939795e+02 1.28901210e+02 1.30000913e+02 1.29831157e+02
 1.26145566e+02 1.24629131e+02 1.23938084e+02 1.22834678e+02
 1.21695175e+02 1.21469938e+02 1.20768028e+02 1.19207040e+02
 1.18746458e+02 1.17890274e+02 1.17106449e+02 1.16913157e+02
 1.15289368e+02 1.15073571e+02 1.14270048e+02 1.13214083e+02
 1.12729976e+02 1.11760772e+02 1.11655960e+02 1.10963571e+02
 1.09193561e+02 1.09253157e+02 1.08664300e+02 1.08329996e+02
 1.07038215e+02 1.06517956e+02 1.05466241e+02 1.04824296e+02
 1.04580681e+02 1.04095905e+02 1.03087771e+02 1.01845712e+02
 9.90162427e+01 1.01000592e+02 1.00549622e+02 9.96783224e+01
 9.99301986e+01 9.802705

In [6]:
MultipliedV=SVDSetupV(Matrix)
def EigenvaluesV(MultipliedV):
    values_V,_=np.linalg.eig(MultipliedV)
    return values_V 
print(EigenvaluesV(MultipliedV))

[6.25760478e+04 1.63428454e+02 1.61253855e+02 1.58353491e+02
 1.56122326e+02 1.53664354e+02 1.52445092e+02 1.50561320e+02
 1.47639034e+02 1.47023322e+02 1.46675680e+02 1.45358785e+02
 1.43374655e+02 1.42130347e+02 1.41602842e+02 1.39920562e+02
 1.38916129e+02 1.37803399e+02 1.37131130e+02 1.34522422e+02
 1.33984396e+02 1.32668668e+02 1.31546758e+02 1.30000913e+02
 1.29831157e+02 1.28901210e+02 1.27939795e+02 1.27354965e+02
 1.26145566e+02 1.24629131e+02 1.23938084e+02 1.22834678e+02
 1.21469938e+02 1.21695175e+02 1.20768028e+02 1.19207040e+02
 1.18746458e+02 1.09253157e+02 1.17890274e+02 1.17106449e+02
 1.16913157e+02 1.15073571e+02 1.15289368e+02 1.14270048e+02
 1.13214083e+02 1.12729976e+02 1.10963571e+02 1.11655960e+02
 1.11760772e+02 1.09193561e+02 1.08664300e+02 1.08329996e+02
 1.07038215e+02 1.06517956e+02 1.05466241e+02 1.04824296e+02
 1.04580681e+02 1.04095905e+02 1.03087771e+02 1.01845712e+02
 1.01000592e+02 1.00549622e+02 9.99301986e+01 9.96783224e+01
 9.90162427e+01 9.802705

In [7]:
values_U=EigenvaluesU(MultipliedU)
def SingularValues(values_U):
    Sing_Values=np.sqrt(values_U)
    Sing_Values=np.sort(Sing_Values)[::-1]
    return Sing_Values
print(SingularValues(values_U))

[2.50152049e+02 1.27839139e+01 1.26985769e+01 1.25838584e+01
 1.24948920e+01 1.23961427e+01 1.23468657e+01 1.22703431e+01
 1.21506804e+01 1.21253174e+01 1.21109735e+01 1.20564831e+01
 1.19739156e+01 1.19218433e+01 1.18996992e+01 1.18288022e+01
 1.17862687e+01 1.17389693e+01 1.17103002e+01 1.15983801e+01
 1.15751629e+01 1.15181886e+01 1.14693835e+01 1.14017943e+01
 1.13943476e+01 1.13534669e+01 1.13110475e+01 1.12851657e+01
 1.12314543e+01 1.11637418e+01 1.11327483e+01 1.10830807e+01
 1.10315536e+01 1.10213401e+01 1.09894508e+01 1.09181976e+01
 1.08970848e+01 1.08577288e+01 1.08215733e+01 1.08126388e+01
 1.07372886e+01 1.07272350e+01 1.06897169e+01 1.06402107e+01
 1.06174373e+01 1.05716967e+01 1.05667384e+01 1.05339248e+01
 1.04524235e+01 1.04495723e+01 1.04242170e+01 1.04081697e+01
 1.03459274e+01 1.03207536e+01 1.02696758e+01 1.02383737e+01
 1.02264696e+01 1.02027400e+01 1.01532148e+01 1.00918637e+01
 1.00499051e+01 1.00274434e+01 9.99650932e+00 9.98390317e+00
 9.95069056e+00 9.900861

In [8]:
Sing_Values=SingularValues(values_U)
def CreateSVArray(Sing_Values, Matrix):
    rows, columns=Matrix.shape
    length=min(rows,columns)
    padded_zero_values= np.pad(Sing_Values,(0,length-len(Sing_Values)),'constant')
    SV_Array=np.zeros((rows,columns), dtype=float)
    np.fill_diagonal(SV_Array, padded_zero_values)
    return SV_Array
print(CreateSVArray(Sing_Values,Matrix))

[[2.50152049e+02 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.27839139e+01 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.26985769e+01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 4.68335973e-02
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.34860284e-02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 3.66348576e-03]]


In [9]:
MultipliedU=SVDSetupU(Matrix)
def EigenvectorsU(MultipliedU):
    _,vectors_U=np.linalg.eig(MultipliedU)
    return vectors_U
print(EigenvectorsU(MultipliedU))

[[ 0.04555148  0.02487831  0.00932219 ...  0.00033731 -0.00048044
   0.00096614]
 [ 0.04678107  0.0604235   0.04337317 ...  0.06120522  0.04568275
   0.00152686]
 [ 0.04441215 -0.02777266 -0.00013042 ... -0.00097245 -0.03357148
   0.04193768]
 ...
 [ 0.0448689  -0.04621462  0.00748257 ... -0.00710551 -0.07558915
   0.00657594]
 [ 0.04449159 -0.01477473 -0.03595519 ... -0.01171992  0.00869879
  -0.02869463]
 [ 0.04637447  0.00512157 -0.07124337 ...  0.00746377  0.01891434
   0.063598  ]]


In [10]:
MultipliedV=SVDSetupV(Matrix)
def EigenvectorsV(MultipliedV):
    _,vectors_V=np.linalg.eig(MultipliedV)
    return vectors_V
print(EigenvectorsV(MultipliedV))

[[ 4.57317109e-02  6.95128245e-02  9.39004541e-03 ...  7.91302665e-04
   2.40217497e-02 -8.06240414e-07]
 [ 4.57423583e-02 -5.54303082e-02 -4.82494586e-02 ...  3.48574716e-03
  -5.03405804e-02  3.36073499e-02]
 [ 4.46186129e-02  2.21910688e-02 -6.83360030e-03 ...  4.17677627e-03
  -2.83868723e-02  4.20442040e-02]
 ...
 [ 4.57180211e-02 -3.89865131e-02  3.90800387e-02 ... -7.59095190e-02
   2.45991865e-02 -1.03251940e-01]
 [ 4.40933320e-02  3.22833598e-02  2.69491829e-02 ... -4.67551189e-02
  -1.53434574e-02  2.08467213e-03]
 [ 4.29103944e-02  2.21091341e-02 -6.09891015e-02 ... -2.45297822e-02
   3.40919867e-02  3.75231294e-02]]


In [11]:
vectors_U=EigenvectorsU(MultipliedU)
def MatrixU(vectors_U):
    matrix_U=np.array(vectors_U)
    magnitude=np.linalg.norm(matrix_U, axis=0)
    matrix_U=matrix_U/magnitude
    return matrix_U
print(MatrixU(vectors_U))

[[ 0.04555148  0.02487831  0.00932219 ...  0.00033731 -0.00048044
   0.00096614]
 [ 0.04678107  0.0604235   0.04337317 ...  0.06120522  0.04568275
   0.00152686]
 [ 0.04441215 -0.02777266 -0.00013042 ... -0.00097245 -0.03357148
   0.04193768]
 ...
 [ 0.0448689  -0.04621462  0.00748257 ... -0.00710551 -0.07558915
   0.00657594]
 [ 0.04449159 -0.01477473 -0.03595519 ... -0.01171992  0.00869879
  -0.02869463]
 [ 0.04637447  0.00512157 -0.07124337 ...  0.00746377  0.01891434
   0.063598  ]]


In [12]:
vectors_V=EigenvectorsV(MultipliedV)
def MatrixV(vectors_V):
    matrix_V=np.array(vectors_V.T)
    return matrix_V
print(MatrixV(vectors_V))

[[ 4.57317109e-02  4.57423583e-02  4.46186129e-02 ...  4.57180211e-02
   4.40933320e-02  4.29103944e-02]
 [ 6.95128245e-02 -5.54303082e-02  2.21910688e-02 ... -3.89865131e-02
   3.22833598e-02  2.21091341e-02]
 [ 9.39004541e-03 -4.82494586e-02 -6.83360030e-03 ...  3.90800387e-02
   2.69491829e-02 -6.09891015e-02]
 ...
 [ 7.91302665e-04  3.48574716e-03  4.17677627e-03 ... -7.59095190e-02
  -4.67551189e-02 -2.45297822e-02]
 [ 2.40217497e-02 -5.03405804e-02 -2.83868723e-02 ...  2.45991865e-02
  -1.53434574e-02  3.40919867e-02]
 [-8.06240414e-07  3.36073499e-02  4.20442040e-02 ... -1.03251940e-01
   2.08467213e-03  3.75231294e-02]]


In [13]:
matrix_U=MatrixU(vectors_U)
SV_Array=CreateSVArray(Sing_Values,Matrix)
matrix_V=MatrixV(vectors_V)
def SVDBuild(matrix_U,SV_Array,matrix_V):
#Perform Singular Value Decomposition, the dot product of Matrices U and A, and the Singular Values Array
    SVD=np.dot(matrix_U, np.dot(SV_Array, matrix_V.T))
    SVD=np.abs(SVD)

    return SVD
print(SVDBuild(matrix_U,SV_Array,matrix_V))
check=np.linalg.svd(Matrix)
print(check)

[[5.31290020e-01 9.91177828e-01 4.41956875e-01 ... 1.19128957e-01
  2.64259852e-01 3.62091774e-02]
 [1.15216215e+00 1.00835404e+00 5.11577821e-02 ... 2.74059832e-01
  5.52569835e-01 3.05508992e-01]
 [5.08723548e-01 8.65653292e-01 2.67773846e-02 ... 2.06580778e-01
  1.67068745e-01 2.92617280e-01]
 ...
 [5.38427904e-02 6.86301875e-01 5.13305476e-02 ... 2.88785321e-04
  3.77119428e-02 3.27975875e-01]
 [6.77366510e-01 1.15613811e+00 4.77516742e-01 ... 3.33595532e-01
  1.29170650e-01 1.63625066e-01]
 [4.01566474e-03 4.26082365e-01 1.32555917e-01 ... 2.87116032e-01
  1.96864515e-03 4.56029051e-01]]
(array([[-0.04555148,  0.02487831, -0.00932219, ...,  0.02514693,
        -0.03683549,  0.0045438 ],
       [-0.04678107,  0.0604235 , -0.04337317, ..., -0.04067773,
         0.03771951,  0.02386735],
       [-0.04441215, -0.02777266,  0.00013042, ...,  0.02453127,
        -0.02837485, -0.04542831],
       ...,
       [-0.0448689 , -0.04621462, -0.00748257, ..., -0.01447685,
        -0.00525929, -